name: Release (version and changelog)
on:
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:

# Needed for nx-set-shas when run on the main branch
permissions:
  actions: read
  contents: write # for checkout and tag
  pull-requests: write # 'write' access to pull requests

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && contains(github.event.commits[0].message, '[skip-ci]') == false
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_PUSH_ACCESS_TOKEN }}

      - name: Git Identity
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email  "${{ github.actor }}@users.noreply.github.com"

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.15.8

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Restore cached npm dependencies
        uses: actions/cache/restore@v3
        with:
          path: |
            node_modules
            ~/.cache/Cypress # needed for the Cypress binary
          key: npm-dependencies-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm install

      - name: Cache npm dependencies
        uses: actions/cache/save@v3
        with:
          path: |
            node_modules
            ~/.cache/Cypress # needed for the Cypress binary
          key: npm-dependencies-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Nx report
        run: pnpm exec nx report

      - name: Build
        run: pnpm exec nx build

      - name: Release
        run: pnpm exec nx release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          NPM_CONFIG_PROVENANCE: true

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.RELEASE_PUSH_ACCESS_TOKEN  }}
          tags: true
          force: true
